In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/train.csv")

df.head()

C:\Users\Gnanasri\AppData\Local\Temp\ipykernel_31536\1140400935.py:4: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/train.csv")

,id,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,22267382,Modern and Cozy Large Studio in Brooklyn,Modern large studio with new amenities and app...,Our place is a little quiet sanctuary in the h...,Modern large studio with new amenities and app...,none,"BAM, Barclays, Brooklyn City Point, Fort Green...",NaN,"Subway: 2,3,4,5,A,C,B,Q,G",Washer/Dryer Dishwasher Internet Gym Roof Top ...,...,10.0,10.0,10.0,t,f,flexible,f,f,1,0.59
1,2473861,Royal Harlem TRIPLEX Home 5 Beds,Harlem is back and so gorgeous! Visit and expl...,Harlem is back and so gorgeous! Visit and expl...,Harlem is back and so gorgeous! Visit and expl...,none,HARLEM is a piece of real NY history overflowi...,HARLEM RESTAURANTS Red Rooster Harlem -- excel...,PUBLIC TRANSPORTATION: Conveniently near all p...,The WHOLE ENTIRE HOUSE,...,9.0,9.0,9.0,t,f,moderate,f,f,3,2.47
2,25079703,Sunny East Village Studio,"Clean, hip and well designed sun drenched East...",This is a rare East Village studio with it's h...,"Clean, hip and well designed sun drenched East...",none,East Village is one of the last remaining neig...,NaN,NaN,You'll have access to the entire space - it's ...,...,10.0,10.0,10.0,f,f,moderate,f,f,1,0.89
3,9342478,"Beautiful, airy, light-filled room","Private, spacious, comfortable room in 2-bed f...","Big closet, two big windows, tall ceiling and ...","Private, spacious, comfortable room in 2-bed f...",none,One block from Morgan L stop. Super cool area....,NaN,NaN,NaN,...,NaN,NaN,NaN,f,f,flexible,f,f,1,NaN
4,4866426,Private Room in Prime Brooklyn Spot,"Comfy, quiet and big private room in a three b...",This big old apartment that we love and take c...,"Comfy, quiet and big private room in a three b...",none,I absolutely love this neighborhood - right at...,Just a note about the space: The window in you...,Super convenient to almost all subway lines. A...,Your room has a very comfortable queen sized b...,...,10.0,10.0,10.0,f,f,flexible,f,f,1,3.14

In [ ]:
df.shape

(33538, 65)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33538 entries, 0 to 33537
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                33538 non-null  int64
 1   name                              33526 non-null  object
 2   summary                           32266 non-null  object
 3   space                             23038 non-null  object
 4   description                       33230 non-null  object
 5   experiences_offered               33538 non-null  object
 6   neighborhood_overview             19948 non-null  object
 7   notes                             13445 non-null  object
 8   transit                           20796 non-null  object
 9   access                            19304 non-null  object
 10  interaction                       18658 non-null  object
 11  house_rules                       19983 non-null  object
 12  host_id                           33538 non-null  int64
 13  host_name                         33533 non-null  object
 14  host_since                        33533 non-null  object
 15  host_location                     33424 non-null  object
 16  host_about                        20374 non-null  object
 17  host_response_time                17345 non-null  object
 18  host_response_rate                17345 non-null  object
 19  host_acceptance_rate              0 non-null      float64
 20  host_is_superhost                 33533 non-null  object
 21  host_neighbourhood                28832 non-null  object
 22  host_listings_count               33533 non-null  float64
 23  host_verifications                33533 non-null  object
 24  host_has_profile_pic              33533 non-null  object
 25  host_identity_verified            33533 non-null  object
 26  neighbourhood_cleansed            33538 non-null  object
 27  neighbourhood_group_cleansed      33538 non-null  object
 28  city                              33499 non-null  object
 29  state                             33528 non-null  object
 30  zipcode                           33053 non-null  object
 31  market                            33448 non-null  object
 32  country_code                      33538 non-null  object
 33  country                           33538 non-null  object
 34  property_type                     33538 non-null  object
 35  room_type                         33538 non-null  object
 36  accommodates                      33538 non-null  int64
 37  bathrooms                         33478 non-null  float64
 38  bedrooms                          33505 non-null  float64
 39  beds                              33507 non-null  float64
 40  bed_type                          33538 non-null  object
 41  amenities                         33538 non-null  object
 42  square_feet                       341 non-null    float64
 43  price                             33538 non-null  float64
 44  guests_included                   33538 non-null  int64
 45  extra_people                      33538 non-null  object
 46  minimum_nights                    33538 non-null  int64
 47  maximum_nights                    33538 non-null  int64
 48  number_of_reviews                 33538 non-null  int64
 49  first_review                      26591 non-null  object
 50  last_review                       26593 non-null  object
 51  review_scores_rating              25874 non-null  float64
 52  review_scores_accuracy            25844 non-null  float64
 53  review_scores_cleanliness         25859 non-null  float64
 54  review_scores_checkin             25829 non-null  float64
 55  review_scores_communication       25849 non-null  float64
 56  review_scores_location            25830 non-null  float64
 57  review_scores_value               25827 non-null  float64
 58  instant_bookable                  33538 non-null  object
 59  is_business_travel_ready          33538 non-null  object
 60  cancellation_policy               33538 non-null  object
 61  require_guest_profile_picture     33538 non-null  object
 62  require_guest_phone_verification  33538 non-null  object
 63  calculated_host_listings_count    33538 non-null  int64
 64  reviews_per_month                 26591 non-null  float64
dtypes: float64(15), int64(8), object(42)
memory usage: 16.6+ MB

In [ ]:
df.isnull().sum()

id                                      0
name                                   12
summary                              1272
space                               10500
description                           308
                                    ...
cancellation_policy                     0
require_guest_profile_picture           0
require_guest_phone_verification        0
calculated_host_listings_count          0
reviews_per_month                    6947
Length: 65, dtype: int64

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.describe()

,id,host_id,host_acceptance_rate,host_listings_count,accommodates,bathrooms,bedrooms,beds,square_feet,price,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,3.353800e+04,3.353800e+04,0.0,33533.000000,33538.000000,33478.000000,33505.000000,33507.000000,341.000000,33538.000000,...,33538.000000,25874.000000,25844.000000,25859.000000,25829.000000,25849.000000,25830.000000,25827.000000,33538.000000,26591.000000
mean,1.566316e+07,5.420691e+07,NaN,10.006799,2.856789,1.141376,1.176869,1.571313,738.958944,145.177291,...,21.635548,93.751488,9.599443,9.255153,9.737466,9.754304,9.500542,9.374647,3.956288,1.429904
std,8.788870e+06,6.149736e+07,NaN,85.869452,1.848491,0.425003,0.744365,1.054226,580.780447,133.085709,...,40.488277,8.315867,0.819684,1.073818,0.706306,0.688775,0.781516,0.888392,12.687366,1.672336
min,2.515000e+03,2.830000e+02,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,8.173466e+06,7.130984e+06,NaN,1.000000,2.000000,1.000000,1.000000,1.000000,400.000000,69.000000,...,1.000000,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.210000
50%,1.633786e+07,2.662292e+07,NaN,1.000000,2.000000,1.000000,1.000000,1.000000,700.000000,109.000000,...,5.000000,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.770000
75%,2.276632e+07,8.248502e+07,NaN,2.000000,4.000000,1.000000,1.000000,2.000000,1000.000000,175.000000,...,23.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,2.140000
max,2.977318e+07,2.240015e+08,NaN,2271.000000,16.000000,16.500000,10.000000,18.000000,5000.000000,1999.000000,...,557.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,132.000000,19.890000

In [ ]:
missing = df.isnull().sum()

missing_percent = (missing / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percent
})

missing_report = missing_report.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_report

                              Missing Values  Missing Percentage
host_acceptance_rate                   33538          100.000000
square_feet                            33197           98.983243
notes                                  20093           59.911146
host_response_rate                     16193           48.282545
host_response_time                     16193           48.282545
...                                      ...                 ...
neighbourhood_group_cleansed               0            0.000000
neighbourhood_cleansed                     0            0.000000
host_id                                    0            0.000000
experiences_offered                        0            0.000000
country_code                               0            0.000000

[65 rows x 2 columns]

In [ ]:
df.nunique().sort_values()

host_acceptance_rate            0
is_business_travel_ready        1
experiences_offered             1
country_code                    2
host_is_superhost               2
                            ...
summary                     30809
amenities                   31365
description                 32436
name                        32883
id                          33538
Length: 65, dtype: int64

In [ ]:
columns_to_check = [
    "host_acceptance_rate",
    "square_feet",
    "is_business_travel_ready",
    "experiences_offered",
    "country_code",
    "host_is_superhost"
]

for col in columns_to_check:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

host_acceptance_rate
host_acceptance_rate
NaN    33538
Name: count, dtype: int64

square_feet
square_feet
NaN       33197
500.0        27
1000.0       27
0.0          22
700.0        20
          ...
915.0         1
925.0         1
1150.0        1
245.0         1
982.0         1
Name: count, Length: 84, dtype: int64

is_business_travel_ready
is_business_travel_ready
f    33538
Name: count, dtype: int64

experiences_offered
experiences_offered
none    33538
Name: count, dtype: int64

country_code
country_code
US    33537
UY        1
Name: count, dtype: int64

host_is_superhost
host_is_superhost
f      28007
t       5526
NaN        5
Name: count, dtype: int64

In [ ]:
columns_to_remove = [
    "host_acceptance_rate",
    "square_feet",
    "is_business_travel_ready",
    "experiences_offered"
]

df_clean = df.drop(columns=columns_to_remove)

df_clean.shape

(33538, 61)

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33538 entries, 0 to 33537
Data columns (total 61 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                33538 non-null  int64
 1   name                              33526 non-null  object
 2   summary                           32266 non-null  object
 3   space                             23038 non-null  object
 4   description                       33230 non-null  object
 5   neighborhood_overview             19948 non-null  object
 6   notes                             13445 non-null  object
 7   transit                           20796 non-null  object
 8   access                            19304 non-null  object
 9   interaction                       18658 non-null  object
 10  house_rules                       19983 non-null  object
 11  host_id                           33538 non-null  int64
 12  host_name                         33533 non-null  object
 13  host_since                        33533 non-null  object
 14  host_location                     33424 non-null  object
 15  host_about                        20374 non-null  object
 16  host_response_time                17345 non-null  object
 17  host_response_rate                17345 non-null  object
 18  host_is_superhost                 33533 non-null  object
 19  host_neighbourhood                28832 non-null  object
 20  host_listings_count               33533 non-null  float64
 21  host_verifications                33533 non-null  object
 22  host_has_profile_pic              33533 non-null  object
 23  host_identity_verified            33533 non-null  object
 24  neighbourhood_cleansed            33538 non-null  object
 25  neighbourhood_group_cleansed      33538 non-null  object
 26  city                              33499 non-null  object
 27  state                             33528 non-null  object
 28  zipcode                           33053 non-null  object
 29  market                            33448 non-null  object
 30  country_code                      33538 non-null  object
 31  country                           33538 non-null  object
 32  property_type                     33538 non-null  object
 33  room_type                         33538 non-null  object
 34  accommodates                      33538 non-null  int64
 35  bathrooms                         33478 non-null  float64
 36  bedrooms                          33505 non-null  float64
 37  beds                              33507 non-null  float64
 38  bed_type                          33538 non-null  object
 39  amenities                         33538 non-null  object
 40  price                             33538 non-null  float64
 41  guests_included                   33538 non-null  int64
 42  extra_people                      33538 non-null  object
 43  minimum_nights                    33538 non-null  int64
 44  maximum_nights                    33538 non-null  int64
 45  number_of_reviews                 33538 non-null  int64
 46  first_review                      26591 non-null  object
 47  last_review                       26593 non-null  object
 48  review_scores_rating              25874 non-null  float64
 49  review_scores_accuracy            25844 non-null  float64
 50  review_scores_cleanliness         25859 non-null  float64
 51  review_scores_checkin             25829 non-null  float64
 52  review_scores_communication       25849 non-null  float64
 53  review_scores_location            25830 non-null  float64
 54  review_scores_value               25827 non-null  float64
 55  instant_bookable                  33538 non-null  object
 56  cancellation_policy               33538 non-null  object
 57  require_guest_profile_picture     33538 non-null  object
 58  require_guest_phone_verification  33538 non-null  object
 59  calculated_host_listings_count    33538 non-null  int64
 60  reviews_per_month                 26591 non-null  float64
dtypes: float64(13), int64(8), object(40)
memory usage: 15.6+ MB

In [ ]:
duplicate_count = df_clean.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [ ]:
duplicate_ids = df_clean["id"].duplicated().sum()

print("Number of duplicate IDs:", duplicate_ids)

Number of duplicate IDs: 0

In [ ]:
print(df_clean.select_dtypes(include="number").columns.tolist())

['id', 'host_id', 'host_listings_count', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price', 'guests_included', 'minimum_nights', 'maximum_nights', 'number_of_reviews', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'calculated_host_listings_count', 'reviews_per_month']

In [ ]:
# Check minimum and maximum values of all numerical columns

numeric_columns = df_clean.select_dtypes(include="number").columns

for col in numeric_columns:
    print(f"\n{col}")
    print("Minimum:", df_clean[col].min())
    print("Maximum:", df_clean[col].max())

id
Minimum: 2515
Maximum: 29773184

host_id
Minimum: 283
Maximum: 224001464

host_listings_count
Minimum: 0.0
Maximum: 2271.0

accommodates
Minimum: 1
Maximum: 16

bathrooms
Minimum: 0.0
Maximum: 16.5

bedrooms
Minimum: 0.0
Maximum: 10.0

beds
Minimum: 0.0
Maximum: 18.0

price
Minimum: 0.0
Maximum: 1999.0

guests_included
Minimum: 1
Maximum: 16

minimum_nights
Minimum: 1
Maximum: 1250

maximum_nights
Minimum: 1
Maximum: 2147483647

number_of_reviews
Minimum: 0
Maximum: 557

review_scores_rating
Minimum: 20.0
Maximum: 100.0

review_scores_accuracy
Minimum: 2.0
Maximum: 10.0

review_scores_cleanliness
Minimum: 2.0
Maximum: 10.0

review_scores_checkin
Minimum: 2.0
Maximum: 10.0

review_scores_communication
Minimum: 2.0
Maximum: 10.0

review_scores_location
Minimum: 2.0
Maximum: 10.0

review_scores_value
Minimum: 2.0
Maximum: 10.0

calculated_host_listings_count
Minimum: 1
Maximum: 132

reviews_per_month
Minimum: 0.01
Maximum: 19.89

In [ ]:
# Check suspicious values

print("PRICE = 0")
print(df_clean[df_clean["price"] == 0][
    ["id", "name", "room_type", "neighbourhood_cleansed", "price"]
])

print("\nBATHROOMS = 0")
print(df_clean[df_clean["bathrooms"] == 0][
    ["id", "name", "room_type", "bathrooms", "bedrooms", "beds"]
])

print("\nBEDROOMS = 0")
print(df_clean[df_clean["bedrooms"] == 0][
    ["id", "name", "room_type", "bedrooms", "beds"]
])

print("\nBEDS = 0")
print(df_clean[df_clean["beds"] == 0][
    ["id", "name", "room_type", "bedrooms", "beds"]
])

PRICE = 0
             id                                               name  \
1223   28107839  Amazing room with rooftop in Chelsea/West Village
1814   20639914       Cozy yet spacious private brownstone bedroom
3375   20728112     Beautiful bedroom w/private garden in Brooklyn
6413   21138538             Lavish 2 BR minutes from Central Park!
10123  18750597  Huge Brooklyn Brownstone Living, Close to it all.
12665  21251256       Room 2B semi-studio in Guesthouse, Manhattan
14021  20277286    Cosy and very central room in Chinatown/Nolita!
16316  20608117                    Sunny, Quiet Room in Greenpoint
17067  20395608    ★ Warm NYC Getaway ★ | Walk/Transit Score 85+ |
18174  20033323                         The Manhattan Duplex Oasis
21354  18539719                    Beautiful bedroom in BushQueens
24440  21304320             Best Coliving space ever! Shared room.
29920  21291569  Coliving in Brooklyn! Modern design / Shared room
31225  20570245                  Luxury Fifth Ave. 2Bdrm Apartment
31344  20933849  Midtown East Studio - quiet & close to everything
33191  20586405                        Rockaway beach Private room

             room_type neighbourhood_cleansed  price
1223      Private room                Chelsea    0.0
1814      Private room     Bedford-Stuyvesant    0.0
3375      Private room     Bedford-Stuyvesant    0.0
6413   Entire home/apt        Upper West Side    0.0
10123     Private room     Bedford-Stuyvesant    0.0
12665     Private room            East Harlem    0.0
14021     Private room              Chinatown    0.0
16316     Private room             Greenpoint    0.0
17067     Private room        East Morrisania    0.0
18174  Entire home/apt                 Harlem    0.0
21354     Private room              Ridgewood    0.0
24440      Shared room               Bushwick    0.0
29920      Shared room               Bushwick    0.0
31225  Entire home/apt                Midtown    0.0
31344  Entire home/apt                Midtown    0.0
33191     Private room                Arverne    0.0

BATHROOMS = 0
             id                                               name  \
340    24834058                                     Queens C Place
1019     673760                    Sunrise Room in Spacious Duplex
1097    8532763                D Rm 12 Sgl Pensione-like Hrt of Bk
1420    8473484                                     Master Bedroom
2823   25374851                         Vintage Custom Van in Soho
3738     199312                        Sunny Space in Williamsburg
4040      15493                     Stay at the CozySuite Fortress
4479   25998072  Sunny & spacious bedroom with amazing views of...
4646   19947590  Stay like a NYker - Cheap, clean and close to All
4703    7127572                Nice and Sunny Bedroom in Brooklyn!
5686   26894687  Cozy, spacious private room in Brooklyn apartment
6844   12379180                 Room in East Village with backyard
7429   10018963                           Private Room on a Budget
7497   19654640                                                NaN
7521   24015301   ~Gorgeous Upper West Central Park Studio NYC!~83
7684   24716751                                             A plus
8313    3974464                 Art Studio Loft in Manhattan (UWS)
8795    5424792                2 SUNNY RMs wparking in huge 3 bdrm
9229    8299030                 AFFORDABLE & COZY IN SUNSET PARK T
10432    158290                Clinton Hill + Free Coffee = #smile
10782   6360224                    Sunny, Private room in Bushwick
11049  14888012                                      Brooklyn Vibe
11541  12601807                         Sunny light filled bedroom
11596   4823105            Cozy Affordable Room Available In NYC!!
11626   5260322          Relaxing Oasis in the midst the City Vibe
12279  14942680                Large bedroom in Williamsburg House
13611   4771964             Bright Brooklyn Bedroom next to Subway
13835  25225344        Studio Apartment in the Heart of Manhattan!
14351  11372085                      Large Double Bedroom NYC FiDi
16527  13821190                        Private room in Astoria, NY
16765   1215627       Floating Cabin Houseboat Rockaway Surf's Up!
17660  10193392                                 great private room
17880  16971895                  West Chelsea Studios - Studio 910
18500  12600938                   Sunny light filled comfy bedroom
20252  21755486     Cute Manhattan bedroom, close to all amenities
20547  23881522  Local hosts. Luxurious room few blocks to Q train
21322     52757                 Park Slope - Big, Bright and Sunny
23010    227715                           ROOM WITH KITCHENETTE #2
23520  15133721           A Clean, Quite, Great room for NY visit.
23902   2495241                 Light Filled Brownstone Front Room
24058    319844                        Cute Room in Historic Loft!
24177   4057361                Large, Bright, Studio-Style Bedroom
25171   6480685                 Cozy, single bed room.15min to NYC
25545   9412636                Safe&Cozy bdoom/5 mins to Manhattan
27310  28918915                     B2. Shared room for 4-5 guests
27616  28580426                     Rooftop Vibes for small events
27808  10119376                        Queen Cabin with Window Two
29241   9283228                           Flushing Elmhurst, House
29588   4127524                Entire 1BD Apt in Long Island City!
29757  14843072                                 Houseboat Hideaway
31103   4483672                       Warm and Cozy Room in Harlem
31227  10656360                         This is a place in the UES
31489  19927574   Go to NYC? Stay with us. Cozy, Clean &Close all.
31723  27086130                          Heaven in New York, Suite
31907  20314852               COMFY BEDROOM IN THE HEART OF HARLEM
31921    401039                    Big and Comfy room near Yankee1
32056  18826197           Room in 3 bedroom house with a backyard!
32685   3544828                PrivateRoom in Beautiful Brownstone
32690   4808505                            Cozy, CLEAN & SAFE room
32963  26668130    Yoga Apartment with Garden @ Brooklyn Yoga Club

             room_type  bathrooms  bedrooms  beds
340       Private room        0.0       1.0   1.0
1019      Private room        0.0       1.0   2.0
1097      Private room        0.0       1.0   1.0
1420      Private room        0.0       1.0   2.0
2823   Entire home/apt        0.0       0.0   1.0
3738      Private room        0.0       1.0   1.0
4040      Private room        0.0       1.0   1.0
4479      Private room        0.0       1.0   1.0
4646      Private room        0.0       1.0   3.0
4703      Private room        0.0       1.0   1.0
5686      Private room        0.0       1.0   1.0
6844      Private room        0.0       1.0   1.0
7429      Private room        0.0       1.0   1.0
7497   Entire home/apt        0.0       2.0   2.0
7521   Entire home/apt        0.0       0.0   2.0
7684      Private room        0.0       1.0   1.0
8313      Private room        0.0       1.0   1.0
8795      Private room        0.0       1.0   1.0
9229      Private room        0.0       1.0   1.0
10432     Private room        0.0       1.0   2.0
10782     Private room        0.0       1.0   1.0
11049     Private room        0.0       1.0   1.0
11541     Private room        0.0       1.0   1.0
11596     Private room        0.0       1.0   1.0
11626     Private room        0.0       1.0   1.0
12279     Private room        0.0       1.0   1.0
13611     Private room        0.0       1.0   3.0
13835  Entire home/apt        0.0       0.0   1.0
14351     Private room        0.0       1.0   1.0
16527     Private room        0.0       1.0   1.0
16765  Entire home/apt        0.0       0.0   0.0
17660     Private room        0.0       1.0   1.0
17880     Private room        0.0       0.0   1.0
18500     Private room        0.0       1.0   1.0
20252     Private room        0.0       1.0   1.0
20547     Private room        0.0       1.0   1.0
21322     Private room        0.0       1.0   1.0
23010  Entire home/apt        0.0       1.0   1.0
23520     Private room        0.0       1.0   1.0
23902     Private room        0.0       3.0   2.0
24058     Private room        0.0       1.0   1.0
24177     Private room        0.0       1.0   1.0
25171     Private room        0.0       1.0   1.0
25545     Private room        0.0       1.0   2.0
27310      Shared room        0.0       1.0   2.0
27616      Shared room        0.0       1.0   1.0
27808     Private room        0.0       1.0   1.0
29241      Shared room        0.0       1.0   1.0
29588  Entire home/apt        0.0       1.0   1.0
29757  Entire home/apt        0.0       2.0   2.0
31103     Private room        0.0       1.0   1.0
31227      Shared room        0.0       1.0   1.0
31489     Private room        0.0       1.0   4.0
31723  Entire home/apt        0.0       1.0   1.0
31907     Private room        0.0       1.0   1.0
31921     Private room        0.0       1.0   1.0
32056     Private room        0.0       1.0   2.0
32685     Private room        0.0       1.0   1.0
32690     Private room        0.0       1.0   1.0
32963     Private room        0.0       1.0   1.0

BEDROOMS = 0
             id                                               name  \
2      25079703                          Sunny East Village Studio
8      27016367     2 Floor duplex Event space for private party's
20     29161249  Times Sq/Bryant Park Studio in #1 HOT LOCATION!!!
23     21900790                       EAST VILLAGE STYLE APARTMENT
28     25045574       Beautiful private room in NYC loft apartment
...         ...                                                ...
33438   6673630                               Stylish L.E.S Studio
33457  20046292  Large Studio + Terrace, steps from Grand Central!
33491  12409217                            Studio Near Time Square
33492  19787245     CHIC & BRIGHT APT ON UES CLOSE TO CENTRAL PARK
33525  10232344                  Cozy studio in heart of Manhattan

             room_type  bedrooms  beds
2      Entire home/apt       0.0   1.0
8      Entire home/apt       0.0   1.0
20     Entire home/apt       0.0   1.0
23     Entire home/apt       0.0   1.0
28        Private room       0.0   1.0
...                ...       ...   ...
33438  Entire home/apt       0.0   1.0
33457  Entire home/apt       0.0   2.0
33491  Entire home/apt       0.0   1.0
33492  Entire home/apt       0.0   2.0
33525  Entire home/apt       0.0   1.0

[3279 rows x 5 columns]

BEDS = 0
             id                                               name  \
37      4799839                 Private Room in Hell's Kitchen NYC
53     25426171     Private room w/ pvt entrance near Times Sq 32C
255    27439827                         Upper East (A Shared room)
287    27700747                     Beach-side basement media room
452    10593675   La Spezia room. Clean, quiet and comfortable bed
...         ...                                                ...
32607  29126779    One Bdrm Apt w/ Extraordinary Views of Downtown
32821  22055300  Cozy Living room sofa bed,close to LGA/JFK/subway
33240    874683                 Spacious Bushwick Duplex Apartment
33424  28561904       Brand new uber-clean minimalist Bushwick 1BR
33437   3721826   Amazing apartment with your old private bathroom

             room_type  bedrooms  beds
37        Private room       1.0   0.0
53        Private room       1.0   0.0
255        Shared room       1.0   0.0
287       Private room       1.0   0.0
452        Shared room       1.0   0.0
...                ...       ...   ...
32607  Entire home/apt       1.0   0.0
32821      Shared room       1.0   0.0
33240     Private room       1.0   0.0
33424  Entire home/apt       1.0   0.0
33437  Entire home/apt       1.0   0.0

[200 rows x 5 columns]

In [ ]:
print("\nMINIMUM NIGHTS >= 365")
print(df_clean[df_clean["minimum_nights"] >= 365][
    ["id", "name", "minimum_nights", "maximum_nights", "price"]
].head(20))

print("\nMAXIMUM NIGHTS >= 10000")
print(df_clean[df_clean["maximum_nights"] >= 10000][
    ["id", "name", "minimum_nights", "maximum_nights", "price"]
].head(20))

MINIMUM NIGHTS >= 365
             id                                               name  \
233     6169897                          Wonderful Large 1 bedroom
1521   21965830              Spacious private room in Hudson Yards
2339    9460661                         Ultra Luxury Apartment NYC
3245    1586935                   Luxury Gramercy Lg 1Bd w Balcony
5681   22761054       Bright spacious Studio overlooking Manhattan
8332   11096888                    Peaceful apartment close to F/G
11112    258690                CHELSEA 1 Bdrm Plus Sleeping Loft!!
12827    649561                 Manhattan Sky Crib (1 year sublet)
13734  23773286                             Available for rent now
13926   6031823  Williamsburg private luxury bedroomYou can't m...
16921   2454507                 Close to everything - Jr 1 bedroom
17527  10514203                Giant Landmark Apartment in the Sky
19589   4204302                   Prime W. Village location 1 bdrm
19835  21151214                  High-end Stunner with River Views
21045   8341919                Brand New Luxury Apt Lease Takeover
22488   2037951                      Modern West Village Apartment
26795   1615764                                                NaN
28232  21399349                 Spacious, sunny, subway 2 min away
28563   3399909                     Super cute and sunny 2 bedroom
29918   8668115                 Zen Room in Crown Heights Brooklyn

       minimum_nights  maximum_nights  price
233               500            6000   75.0
1521              365             720   70.0
2339              365            1125  219.0
3245              365            1125  250.0
5681              365            1000  120.0
8332              500            1125   45.0
11112             365             365  195.0
12827             365            1125  135.0
13734             365            1125  350.0
13926             365           10000  100.0
16921             365            2000  130.0
17527             365            1125  350.0
19589            1250            1250  180.0
19835             365            1125  600.0
21045             480            1125  199.0
22488             365            1125  500.0
26795            1000            1125  400.0
28232             900            1125   52.0
28563             365            1125  240.0
29918             500            1125   50.0

MAXIMUM NIGHTS >= 10000
             id                                               name  \
4443    4173664                  Cozy, Convenient Williamsburg Apt
9866    2793630     Gorgeous Loft in Prime Location 2 with Rooftop
10276   3851498                                                  L
12957   7693424                          Shared Apartment to share
13926   6031823  Williamsburg private luxury bedroomYou can't m...
18710   6357527                         Great UWS Studio Apartment
21162  15912119                  Cozy bedroom close to centralpark
21508  18024805                      BROADWAY MANHATTAN LUXURY APT
22819   6305027                    Beautiful Boerum Hill 2 Bedroom
24729  17512883       Amazing 1 Bedroom | 1 Bedroom | Skyline View
33344   4660022                     Best Block Luxury Loft in SoHo

       minimum_nights  maximum_nights   price
4443                1           99999   172.0
9866                5           60000   120.0
10276              30           99999    65.0
12957               1        20000000   100.0
13926             365           10000   100.0
18710               2      2147483647   130.0
21162               2          112000   120.0
21508              30           99999   270.0
22819              30        20000000   175.0
24729              30           15000   135.0
33344               1         1000000  1100.0

In [ ]:
print("Number of listings with price = 0:",
      (df_clean["price"] == 0).sum())

print("Number of listings with minimum_nights >= 365:",
      (df_clean["minimum_nights"] >= 365).sum())

print("Number of listings with maximum_nights >= 10000:",
      (df_clean["maximum_nights"] >= 10000).sum())

print("Number of listings with maximum_nights = 2147483647:",
      (df_clean["maximum_nights"] == 2147483647).sum())

Number of listings with price = 0: 16
Number of listings with minimum_nights >= 365: 21
Number of listings with maximum_nights >= 10000: 11
Number of listings with maximum_nights = 2147483647: 1

In [ ]:
df_clean[df_clean["maximum_nights"] >= 10000][
    ["id", "name", "minimum_nights", "maximum_nights", "price"]
].sort_values("maximum_nights", ascending=False).head(20)

,id,name,minimum_nights,maximum_nights,price
18710,6357527,Great UWS Studio Apartment,2,2147483647,130.0
12957,7693424,Shared Apartment to share,1,20000000,100.0
22819,6305027,Beautiful Boerum Hill 2 Bedroom,30,20000000,175.0
33344,4660022,Best Block Luxury Loft in SoHo,1,1000000,1100.0
21162,15912119,Cozy bedroom close to centralpark,2,112000,120.0
4443,4173664,"Cozy, Convenient Williamsburg Apt",1,99999,172.0
10276,3851498,L,30,99999,65.0
21508,18024805,BROADWAY MANHATTAN LUXURY APT,30,99999,270.0
9866,2793630,Gorgeous Loft in Prime Location 2 with Rooftop,5,60000,120.0
24729,17512883,Amazing 1 Bedroom | 1 Bedroom | Skyline View,30,15000,135.0
13926,6031823,Williamsburg private luxury bedroomYou can't m...,365,10000,100.0

In [ ]:
df_clean[df_clean["price"] == 0][
    ["id", "name", "room_type", "neighbourhood_cleansed", "price"]
].head(20)

,id,name,room_type,neighbourhood_cleansed,price
1223,28107839,Amazing room with rooftop in Chelsea/West Village,Private room,Chelsea,0.0
1814,20639914,Cozy yet spacious private brownstone bedroom,Private room,Bedford-Stuyvesant,0.0
3375,20728112,Beautiful bedroom w/private garden in Brooklyn,Private room,Bedford-Stuyvesant,0.0
6413,21138538,Lavish 2 BR minutes from Central Park!,Entire home/apt,Upper West Side,0.0
10123,18750597,"Huge Brooklyn Brownstone Living, Close to it all.",Private room,Bedford-Stuyvesant,0.0
12665,21251256,"Room 2B semi-studio in Guesthouse, Manhattan",Private room,East Harlem,0.0
14021,20277286,Cosy and very central room in Chinatown/Nolita!,Private room,Chinatown,0.0
16316,20608117,"Sunny, Quiet Room in Greenpoint",Private room,Greenpoint,0.0
17067,20395608,★ Warm NYC Getaway ★ | Walk/Transit Score 85+ |,Private room,East Morrisania,0.0
18174,20033323,The Manhattan Duplex Oasis,Entire home/apt,Harlem,0.0
21354,18539719,Beautiful bedroom in BushQueens,Private room,Ridgewood,0.0
24440,21304320,Best Coliving space ever! Shared room.,Shared room,Bushwick,0.0
29920,21291569,Coliving in Brooklyn! Modern design / Shared room,Shared room,Bushwick,0.0
31225,20570245,Luxury Fifth Ave. 2Bdrm Apartment,Entire home/apt,Midtown,0.0
31344,20933849,Midtown East Studio - quiet & close to everything,Entire home/apt,Midtown,0.0
33191,20586405,Rockaway beach Private room,Private room,Arverne,0.0

In [ ]:
# Remove listings with zero price
df_clean = df_clean[df_clean["price"] > 0].copy()

# Replace the clearly invalid maximum_nights value
df_clean.loc[
    df_clean["maximum_nights"] == 2147483647,
    "maximum_nights"
] = np.nan

print("Shape after invalid-value cleaning:", df_clean.shape)

Shape after invalid-value cleaning: (33522, 61)

In [ ]:
print("Zero-price listings:", (df_clean["price"] == 0).sum())
print("Invalid maximum_nights:",
      (df_clean["maximum_nights"] == 2147483647).sum())

Zero-price listings: 0
Invalid maximum_nights: 0

In [ ]:
print(df_clean["price"].describe())

count    33522.000000
mean       145.246584
std        133.079657
min         10.000000
25%         69.000000
50%        109.000000
75%        175.000000
max       1999.000000
Name: price, dtype: float64

In [ ]:
# Calculate IQR for price

Q1 = df_clean["price"].quantile(0.25)
Q3 = df_clean["price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

# Count potential outliers
price_outliers = df_clean[
    (df_clean["price"] < lower_bound) |
    (df_clean["price"] > upper_bound)
]

print("Number of potential price outliers:", len(price_outliers))

Q1: 69.0
Q3: 175.0
IQR: 106.0
Lower Bound: -90.0
Upper Bound: 334.0
Number of potential price outliers: 2033

In [ ]:
price_outliers = df_clean[
    df_clean["price"] > upper_bound
]

price_outliers[[
    "id",
    "name",
    "neighbourhood_cleansed",
    "room_type",
    "accommodates",
    "bedrooms",
    "bathrooms",
    "price"
]].sort_values("price", ascending=False).head(20)

,id,name,neighbourhood_cleansed,room_type,accommodates,bedrooms,bathrooms,price
23670,1976123,Huge Loft with Private Entrance,East Village,Entire home/apt,2,1.0,1.0,1999.0
19918,22295960,Chelsea Gallery Space for events and exhibitions,Chelsea,Private room,16,0.0,1.0,1860.0
18534,16720831,Unique Vintage Loft & Roof Deck,Williamsburg,Entire home/apt,16,0.0,6.0,1820.0
28969,9430805,Huge 5BR loft with full kitchen/dining for hol...,Gramercy,Entire home/apt,15,5.0,2.0,1800.0
5633,11234747,Mins away to Manhattan Suite Residence,Astoria,Shared room,2,1.0,1.0,1800.0
32331,28132190,Smyth Suite at Smyth Tribeca,Midtown,Private room,2,1.0,1.5,1799.0
5132,22782930,Bushwick Gallery Spot,Williamsburg,Entire home/apt,16,0.0,3.0,1750.0
6603,2210561,"4 Br, Tribeca, Walking Dist to PATH",Tribeca,Entire home/apt,8,4.0,2.0,1750.0
15748,10314411,Ultra-Modern 6-bedroom House (Great for Groups),Chelsea,Entire home/apt,16,6.0,3.5,1731.0
6012,29542012,Gorgeous Bohemian one BEDROOM in EAST VILLAGE,East Village,Private room,1,0.0,1.0,1700.0
22146,27222175,Private Bedroom in the Financial District,Financial District,Private room,1,1.0,1.0,1700.0
11043,1861281,Carol,East Village,Private room,1,1.0,1.0,1700.0
7968,2307885,Stunning 2600ft full floor LOFT,Chelsea,Entire home/apt,5,2.0,2.0,1650.0
31261,28699177,Quiet Large Bedroom / Living Rm,Greenpoint,Private room,2,1.0,1.0,1600.0
22083,16087406,2 BDRM Presidential Reserve at Wyndham Midtown 45,Midtown,Private room,6,2.0,2.0,1599.0
26977,20959500,Apartment For Rent,Williamsburg,Private room,1,1.0,2.0,1560.0
2263,28356870,Magical home luxury Upper East Side Central Park.,Upper East Side,Entire home/apt,10,4.0,2.5,1500.0
28752,2298711,Perfect for SB - UES apt for 4 ppl,Upper East Side,Entire home/apt,4,1.0,1.0,1500.0
24967,29360954,Dramatic Duplex Soho Loft,SoHo,Entire home/apt,5,3.0,5.0,1500.0
3541,2243984,Superbowl in the West Village,West Village,Entire home/apt,4,2.0,2.0,1500.0

In [ ]:
[col for col in df_clean.columns if "neigh" in col.lower() or "location" in col.lower()]

['neighborhood_overview',
 'host_location',
 'host_neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'review_scores_location']

In [ ]:
numeric_columns = [
    "host_listings_count",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "minimum_nights",
    "maximum_nights"
]

for col in numeric_columns:
    print(f"\n--- {col} ---")
    print(df_clean[col].describe())

--- host_listings_count ---
count    33517.000000
mean        10.009160
std         85.889845
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max       2271.000000
Name: host_listings_count, dtype: float64

--- accommodates ---
count    33522.000000
mean         2.856840
std          1.848696
min          1.000000
25%          2.000000
50%          2.000000
75%          4.000000
max         16.000000
Name: accommodates, dtype: float64

--- bathrooms ---
count    33462.000000
mean         1.140981
std          0.423072
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         16.500000
Name: bathrooms, dtype: float64

--- bedrooms ---
count    33489.000000
mean         1.176864
std          0.744454
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         10.000000
Name: bedrooms, dtype: float64

--- beds ---
count    33491.000000
mean         1.571049
std          1.054072
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max         18.000000
Name: beds, dtype: float64

--- minimum_nights ---
count    33522.000000
mean         6.843625
std         19.784861
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max       1250.000000
Name: minimum_nights, dtype: float64

--- maximum_nights ---
count    3.352100e+04
mean     1.849866e+03
std      1.545795e+05
min      1.000000e+00
25%      2.900000e+01
50%      1.124000e+03
75%      1.125000e+03
max      2.000000e+07
Name: maximum_nights, dtype: float64

In [ ]:
df_clean[
    ["id", "host_id", "host_listings_count", "name"]
].sort_values(
    "host_listings_count",
    ascending=False
).head(20)

,id,host_id,host_listings_count,name
6186,27931467,92676764,2271.0,Feel The Buzz Of The Big City At Midtown 45!
33017,27931471,92676764,2271.0,Experience All Of New Yorks Excitement At Midtown
22332,18521455,92676764,2271.0,Escape Every Day Life At Midtown 45!
14398,27931470,92676764,2271.0,Take In The Creativity Of New York At Midtown 45!
24104,27931466,92676764,2271.0,Enjoy The Views Of New York At Midtown 45!
32430,20211205,92676764,2271.0,Midtown 45: Moments From The Rockefeller Center!
16740,27931468,92676764,2271.0,Visit the Rockefeller Center Nearby Midtown 45!
32194,20211217,92676764,2271.0,See The Big Apple While Staying At Midtown 45!
7910,20211212,92676764,2271.0,See everything NYC has to offer with Midtown 45!
6737,26552951,12243051,1477.0,Serene 1BR in Chelsea by Sonder
33407,28367264,12243051,1477.0,Spacious 1BR in Midtown East by Sonder
32310,28104307,12243051,1477.0,Prestigious 1BR on Madison Avenue by Sonder
3890,26450834,12243051,1477.0,Colorful 1BR in Midtown East by Sonder
6277,27369200,12243051,1477.0,Colorful 1BR in Chelsea by Sonder
28154,24751022,12243051,1477.0,Modern 1BR in FiDi by Sonder
2105,26198109,12243051,1477.0,Modern 1BR in Midtown East by Sonder
17730,23874777,12243051,1477.0,Lively 1BR in FiDi by Sonder
1205,23714684,12243051,1477.0,Stunning 1BR in FiDi by Sonder
18434,26450808,12243051,1477.0,Vibrant 1BR in FiDi by Sonder
6328,28127032,12243051,1477.0,Prestigious 2BR in Financial District by Sonder

In [ ]:
df_clean[
    ["id", "name", "accommodates", "bedrooms", "beds", "bathrooms", "price"]
].sort_values(
    "bathrooms",
    ascending=False
).head(20)

,id,name,accommodates,bedrooms,beds,bathrooms,price
1024,23624930,Lisa's Comfort Zone,2,1.0,1.0,16.5,70.0
5546,19141662,Brand New shared room in CoLiving (M and L tra...,2,1.0,2.0,8.0,30.0
16587,23932185,Cozy private room / Williamsburg / L train,2,1.0,1.0,7.0,65.0
1519,23792606,Newest private room / 15 mins to Manhattan,1,1.0,1.0,7.0,65.0
2184,23797329,Newly & Comfy Shared room close to Manhattan,2,1.0,2.0,7.0,35.0
3477,26211176,Shared room in East Williamsburg near the park,4,1.0,4.0,6.5,35.0
20261,22237320,Modern Room in Coliving/15min walk to Williams...,2,1.0,2.0,6.5,35.0
3359,26933416,Comfy shared room near Subway close to Manhattan,2,1.0,2.0,6.5,41.0
22926,21660113,Great shared house / Bushwick!,3,1.0,3.0,6.5,30.0
14423,22349506,Shared room in nice surroundings in Ridgewood!!,3,1.0,3.0,6.0,27.0
17776,28877613,Super Spacious & great location!!!3 bed 2 bath...,7,3.0,5.0,6.0,599.0
15177,18935359,Magnificent Lakeview Home on Kissena Park,16,10.0,15.0,6.0,1000.0
7475,22221072,Private cozy room in Bushwick / full-size bed,2,1.0,1.0,6.0,50.0
16618,25947689,Modern 6 bedrooms 6 baths/backyard- no party,16,6.0,8.0,6.0,500.0
1661,19196911,Beautiful shared room in Modern CoLiving space,3,1.0,3.0,6.0,27.0
25403,19141112,Modern CoLiving at Ridgewood / shared room,2,1.0,2.0,6.0,30.0
16658,26706133,Beautiful brand new apartment !,12,6.0,6.0,6.0,860.0
18534,16720831,Unique Vintage Loft & Roof Deck,16,0.0,1.0,6.0,1820.0
7093,21292185,"Great shared room / Best price, high quality!",3,1.0,3.0,6.0,29.0
28144,17405172,ENTIRE Home! 10BR/6BA + Private Garden SLEEPS 20+,16,10.0,13.0,6.0,695.0

In [ ]:
df_clean[
    ["id", "name", "minimum_nights", "maximum_nights", "price"]
].sort_values(
    "minimum_nights",
    ascending=False
).head(20)

,id,name,minimum_nights,maximum_nights,price
19589,4204302,Prime W. Village location 1 bdrm,1250,1250.0,180.0
26795,1615764,NaN,1000,1125.0,400.0
28232,21399349,"Spacious, sunny, subway 2 min away",900,1125.0,52.0
8332,11096888,Peaceful apartment close to F/G,500,1125.0,45.0
29918,8668115,Zen Room in Crown Heights Brooklyn,500,1125.0,50.0
233,6169897,Wonderful Large 1 bedroom,500,6000.0,75.0
21045,8341919,Brand New Luxury Apt Lease Takeover,480,1125.0,199.0
32724,992977,Park Slope Pre-War Apartment,365,365.0,100.0
13734,23773286,Available for rent now,365,1125.0,350.0
11112,258690,CHELSEA 1 Bdrm Plus Sleeping Loft!!,365,365.0,195.0
19835,21151214,High-end Stunner with River Views,365,1125.0,600.0
22488,2037951,Modern West Village Apartment,365,1125.0,500.0
13926,6031823,Williamsburg private luxury bedroomYou can't m...,365,10000.0,100.0
28563,3399909,Super cute and sunny 2 bedroom,365,1125.0,240.0
16921,2454507,Close to everything - Jr 1 bedroom,365,2000.0,130.0
5681,22761054,Bright spacious Studio overlooking Manhattan,365,1000.0,120.0
1521,21965830,Spacious private room in Hudson Yards,365,720.0,70.0
17527,10514203,Giant Landmark Apartment in the Sky,365,1125.0,350.0
2339,9460661,Ultra Luxury Apartment NYC,365,1125.0,219.0
12827,649561,Manhattan Sky Crib (1 year sublet),365,1125.0,135.0

In [ ]:
df_clean[
    ["id", "name", "minimum_nights", "maximum_nights", "price"]
].sort_values(
    "maximum_nights",
    ascending=False
).head(20)

,id,name,minimum_nights,maximum_nights,price
22819,6305027,Beautiful Boerum Hill 2 Bedroom,30,20000000.0,175.0
12957,7693424,Shared Apartment to share,1,20000000.0,100.0
33344,4660022,Best Block Luxury Loft in SoHo,1,1000000.0,1100.0
21162,15912119,Cozy bedroom close to centralpark,2,112000.0,120.0
10276,3851498,L,30,99999.0,65.0
4443,4173664,"Cozy, Convenient Williamsburg Apt",1,99999.0,172.0
21508,18024805,BROADWAY MANHATTAN LUXURY APT,30,99999.0,270.0
9866,2793630,Gorgeous Loft in Prime Location 2 with Rooftop,5,60000.0,120.0
24729,17512883,Amazing 1 Bedroom | 1 Bedroom | Skyline View,30,15000.0,135.0
13926,6031823,Williamsburg private luxury bedroomYou can't m...,365,10000.0,100.0
32507,19802824,The Amsterdam - A Luxury Apartment,2,9999.0,250.0
12819,19179863,Periwinkle in Cypress Hills,2,9999.0,39.0
31531,25638433,Beautiful Cozy Shared Apartment by Times Square,1,9999.0,65.0
32595,18747972,Moore St. Bushwick Loft,2,9999.0,185.0
15447,20520689,The Belvedere - A Luxury One Bedroom with Loft,2,9999.0,175.0
17170,19141812,Mint Green in Cypress Hills,2,9999.0,52.0
12696,19179961,Orange in Cypress Hills,2,9999.0,65.0
233,6169897,Wonderful Large 1 bedroom,500,6000.0,75.0
23339,14153081,Vibrant Apartment with Backyard Oasis in Bushwick,2,5000.0,111.0
25233,3311821,Williamsburg COZY SUNNY next2train!,3,4000.0,100.0

In [ ]:
print(
    df_clean["maximum_nights"]
    .value_counts(dropna=False)
    .sort_index(ascending=False)
    .head(20)
)

maximum_nights
20000000.0    2
1000000.0     1
112000.0      1
99999.0       3
60000.0       1
15000.0       1
10000.0       1
9999.0        7
6000.0        1
5000.0        1
4000.0        2
3020.0        1
3000.0        4
2000.0        6
1825.0        6
1800.0        1
1508.0        1
1365.0        1
1300.0        1
1250.0        1
Name: count, dtype: int64

In [ ]:
df_clean[
    ["id", "name", "accommodates", "bedrooms",
     "beds", "bathrooms", "price"]
].sort_values(
    "bathrooms", ascending=False
).head(20)

,id,name,accommodates,bedrooms,beds,bathrooms,price
1024,23624930,Lisa's Comfort Zone,2,1.0,1.0,16.5,70.0
5546,19141662,Brand New shared room in CoLiving (M and L tra...,2,1.0,2.0,8.0,30.0
16587,23932185,Cozy private room / Williamsburg / L train,2,1.0,1.0,7.0,65.0
1519,23792606,Newest private room / 15 mins to Manhattan,1,1.0,1.0,7.0,65.0
2184,23797329,Newly & Comfy Shared room close to Manhattan,2,1.0,2.0,7.0,35.0
3477,26211176,Shared room in East Williamsburg near the park,4,1.0,4.0,6.5,35.0
20261,22237320,Modern Room in Coliving/15min walk to Williams...,2,1.0,2.0,6.5,35.0
3359,26933416,Comfy shared room near Subway close to Manhattan,2,1.0,2.0,6.5,41.0
22926,21660113,Great shared house / Bushwick!,3,1.0,3.0,6.5,30.0
14423,22349506,Shared room in nice surroundings in Ridgewood!!,3,1.0,3.0,6.0,27.0
17776,28877613,Super Spacious & great location!!!3 bed 2 bath...,7,3.0,5.0,6.0,599.0
15177,18935359,Magnificent Lakeview Home on Kissena Park,16,10.0,15.0,6.0,1000.0
7475,22221072,Private cozy room in Bushwick / full-size bed,2,1.0,1.0,6.0,50.0
16618,25947689,Modern 6 bedrooms 6 baths/backyard- no party,16,6.0,8.0,6.0,500.0
1661,19196911,Beautiful shared room in Modern CoLiving space,3,1.0,3.0,6.0,27.0
25403,19141112,Modern CoLiving at Ridgewood / shared room,2,1.0,2.0,6.0,30.0
16658,26706133,Beautiful brand new apartment !,12,6.0,6.0,6.0,860.0
18534,16720831,Unique Vintage Loft & Roof Deck,16,0.0,1.0,6.0,1820.0
7093,21292185,"Great shared room / Best price, high quality!",3,1.0,3.0,6.0,29.0
28144,17405172,ENTIRE Home! 10BR/6BA + Private Garden SLEEPS 20+,16,10.0,13.0,6.0,695.0